/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dong_develop_utils_Secret */

#ifndef _Included_com_dong_develop_utils_Secret
#define _Included_com_dong_develop_utils_Secret
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dong_develop_utils_Secret
 * Method:    getUmkey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dong_develop_utils_Secret_getUmkey
  (JNIEnv *env, jclass obj){
    return (*env)->NewStringUTF(env,"59759e781c5dd03d93000e39");
};

#ifdef __cplusplus
}
#endif
#endif
