/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dong_develop_utils_NDK */

#ifndef _Included_com_dong_develop_utils_NDK
#define _Included_com_dong_develop_utils_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dong_develop_utils_NDK
 * Method:    getTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dong_develop_utils_NDK_getTime
  (JNIEnv *, jobject);

/*
 * Class:     com_dong_develop_utils_NDK
 * Method:    getTime1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dong_develop_utils_NDK_getTime1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
